version: '3.8'

services:
  prod:
    container_name: prod
    build:
      context: ..
      dockerfile: ../Dockerfile.prod
      args:
        JAR_FILE: /build/libs/*.jar
    image: woowajeff/todoktodok:prod
    ports:
      - "80:8080"
    volumes:
      - ../log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  promtail:
    container_name: promtail_prod
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ../config/promtail-config-prod.yml:/etc/promtail/promtail.yml
      - ../log:/log
      - promtail_positions:/tmp/positions-prod.yaml
    command: -config.file=/etc/promtail/promtail.yml
    restart: always

volumes:
  promtail_positions:
