version: '3.8'

services:
  practice:
    container_name: practice
    build:
      context: ..
      dockerfile: ../Dockerfile.practice
      args:
        JAR_FILE: /build/libs/*.jar
    image: woowajeff/todoktodok:practice
    ports:
      - "80:8080"
    volumes:
      - ../log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=practice
    restart: always
    networks:
      - practice_network

networks:
  practice_network:
    external: true
