version: '3.8'

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        JAR_FILE: /build/libs/*.jar
    image: woowajeff/todoktodok:dev
    ports:
      - "80:8080"
    volumes:
      - ./log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev-network

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail.yml
      - ./log:/log
    command: -config.file=/etc/promtail/promtail.yml
    restart: always
    networks:
      - dev-network

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: todoktodokdb
      MYSQL_DATABASE: todoktodok_dev_db
    ports:
      - "3306:3306"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptodoktodokdb"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  dev-network:
    driver: bridge
