spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  config:
    import:
      - submodule/security/aladin.yml
      - submodule/security/jwt.yml

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true

aladin:
  base-url: ${aladin.base-url}
  item-search-uri: ${aladin.item-search-uri}
  api-key: ${aladin.api-key}
  item-lookup-uri: ${aladin.item-lookup-uri}

jwt:
  access-token:
    expire-mills: ${jwt.access-token.expire-mills}
  temp-token:
    expire-mills: ${jwt.temp-token.expire-mills}
