name: Backend CI/CD

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ "backend/**" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Assemble Build
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build & Push
        run: |
          docker buildx build --platform linux/arm64 -t woowajeff/todoktodok:latest --push .

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull woowajeff/todoktodok:latest

      - name: Run docker image
        run: |
          docker run -d -p 80:8080 woowajeff/todoktodok

      - name: Docker image Prune
        run: |
          sudo docker image prune -af
